task:
    and, or, not, nand, nor gate
    - no function no numpy
    - function no numpy
    - numpy

1. No Function and No Numpy

In [3]:
data = [
    (-1, -1, -1),  # AND(-1, -1) -> -1
    (-1,  1, -1),  # AND(-1,  1) -> -1
    ( 1, -1, -1),  # AND( 1, -1) -> -1
    ( 1,  1,  1)   # AND( 1,  1) -> 1
]
w1, w2, bias = 0, 0, 0

# Training Phase
print(f"X1  X2  y W1  W2  b  ")
for x1, x2, y in data:
    print(f"{x1}  {x2}  {y} {w1}  {w2}")
    w1 += x1 * y
    w2 += x2 * y
    bias += y
print("*****"*15)
print(f"Trained Weights: w1={w1}, w2={w2}, bias={bias}")
print(f"X1  X2  W1  W2  b  Y")
# Testing Phase
for x1, x2, y in data:
    net = w1 * x1 + w2 * x2 + bias
    r = 1 if net >= 0 else -1
    print(f"{x1}  {x2}  {w1}  {w2}  {net} {r}")

X1  X2  y W1  W2  b  
-1  -1  -1 0  0
-1  1  -1 1  1
1  -1  -1 2  0
1  1  1 1  1
***************************************************************************
Trained Weights: w1=2, w2=2, bias=-2
X1  X2  W1  W2  b  Y
-1  -1  2  2  -6 -1
-1  1  2  2  -2 -1
1  -1  2  2  -2 -1
1  1  2  2  2 1


In [1]:
#Hebbian Learning for AND Gate
# Using -1 instead of 0 and threshold of 0

# Training Data (Inputs and Expected Outputs)
data = [
    (-1, -1, -1),  # AND(-1, -1) -> -1
    (-1,  1, -1),  # AND(-1,  1) -> -1
    ( 1, -1, -1),  # AND( 1, -1) -> -1
    ( 1,  1,  1)   # AND( 1,  1) -> 1
]

# Initialize weights and bias
w1, w2, bias = 0, 0, 0

# Training Phase
print(f"X1  X2  y W1  W2  b  ")
for x1, x2, y in data:
    print(f"{x1}  {x2}  {y} {w1}  {w2}")
    w1 += x1 * y
    w2 += x2 * y
    bias += y

print(f"Trained Weights: w1={w1}, w2={w2}, bias={bias}")
print(f"X1  X2  W1  W2  b  Y")
# Testing Phase
for x1, x2, y in data:
    net = w1 * x1 + w2 * x2 + bias
    r = 1 if net >= 0 else -1
    print(f"{x1}  {x2}  {w1}  {w2}  {net} {r}")


X1  X2  y W1  W2  b  
-1  -1  -1 0  0
-1  1  -1 1  1
1  -1  -1 2  0
1  1  1 1  1
Trained Weights: w1=2, w2=2, bias=-2
X1  X2  W1  W2  b  Y
-1  -1  2  2  -6 -1
-1  1  2  2  -2 -1
1  -1  2  2  -2 -1
1  1  2  2  2 1


In [2]:
# Hebbian Learning for AND Gate
# Using -1 instead of 0 and threshold of 0

def train_hebbian(data):
    w1, w2, bias = 0, 0, 0
    print(f"X1  X2  y W1  W2  b  ")
    for x1, x2, y in data:
        print(f"{x1}  {x2}  {y} {w1}  {w2}")
        w1 += x1 * y
        w2 += x2 * y
        bias += y
    print(f"Trained Weights: w1={w1}, w2={w2}, bias={bias}")
    return w1, w2, bias

def test_hebbian(data, w1, w2, bias):
    print(f"X1  X2  W1  W2  b  Y")
    for x1, x2, y in data:
        net = w1 * x1 + w2 * x2 + bias
        r = 1 if net >= 0 else -1
        print(f"{x1}  {x2}  {w1}  {w2}  {net} {r}")

# Training Data (Inputs and Expected Outputs)
data = [
    (-1, -1, -1),  # AND(-1, -1) -> -1
    (-1,  1, -1),  # AND(-1,  1) -> -1
    ( 1, -1, -1),  # AND( 1, -1) -> -1
    ( 1,  1,  1)   # AND( 1,  1) -> 1
]

# Train the model
w1, w2, bias = train_hebbian(data)

# Test the model
test_hebbian(data, w1, w2, bias)

X1  X2  y W1  W2  b  
-1  -1  -1 0  0
-1  1  -1 1  1
1  -1  -1 2  0
1  1  1 1  1
Trained Weights: w1=2, w2=2, bias=-2
X1  X2  W1  W2  b  Y
-1  -1  2  2  -6 -1
-1  1  2  2  -2 -1
1  -1  2  2  -2 -1
1  1  2  2  2 1


In [3]:
###Importing NumPy

import numpy as np

##Creating Arrays

a = np.array([1, 2, 3])  # 1D array
b = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

###Shape & Size

print(a.shape)  # (3,)
print(b.shape)  # (2, 3)
print(b.size)   # 6 (total elements)

####Generating Arrays

zeros = np.zeros((2, 3))  # 2x3 matrix of zeros
ones = np.ones((3, 3))    # 3x3 matrix of ones
rand = np.random.rand(3, 3)  # 3x3 matrix of random values

####Basic Operations

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)  # [5 7 9] (element-wise addition)
print(x * y)  # [4 10 18] (element-wise multiplication)
print(np.dot(x, y))  # 32 (dot product)

###Matrix Multiplication

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication

####Mean, Sum, Max

arr = np.array([1, 2, 3, 4])
print(np.mean(arr))  # 2.5
print(np.sum(arr))   # 10
print(np.max(arr))   # 4

###Conditional Selection

arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 2])  # [3 4 5] (elements that are greater than 2)

(3,)
(2, 3)
6
[5 7 9]
[ 4 10 18]
32
[[19 22]
 [43 50]]
2.5
10
4
[3 4 5]


In [4]:
import numpy as np

# Hebbian Learning for AND Gate
# Using -1 instead of 0 and threshold of 0

w = np.zeros(2)
bias = 0
print(f"X1  X2  y  W1  W2  b")
for x1, x2, y in [
    (-1, -1, -1),
    (-1,  1, -1),
    ( 1, -1, -1),
    ( 1,  1,  1)
]:
    print(f"{x1}  {x2}  {y}  {w[0]}  {w[1]}  {bias}")
    w += np.array([x1, x2]) * y
    bias += y
print(f"Trained Weights: w1={w[0]}, w2={w[1]}, bias={bias}")

print(f"X1  X2  W1  W2  b  Y")
for x1, x2, y in [
    (-1, -1, -1),
    (-1,  1, -1),
    ( 1, -1, -1),
    ( 1,  1,  1)
]:
    net = np.dot(w, np.array([x1, x2])) + bias
    r = 1 if net >= 0 else -1
    print(f"{x1}  {x2}  {w[0]}  {w[1]}  {bias}  {r}")

X1  X2  y  W1  W2  b
-1  -1  -1  0.0  0.0  0
-1  1  -1  1.0  1.0  -1
1  -1  -1  2.0  0.0  -2
1  1  1  1.0  1.0  -3
Trained Weights: w1=2.0, w2=2.0, bias=-2
X1  X2  W1  W2  b  Y
-1  -1  2.0  2.0  -2  -1
-1  1  2.0  2.0  -2  -1
1  -1  2.0  2.0  -2  -1
1  1  2.0  2.0  -2  1


In [5]:
import numpy as np

# Hebbian Learning for AND Gate
# Using -1 instead of 0 and threshold of 0

def train_hebbian(data):
    w = np.zeros(2)
    bias = 0
    print(f"X1  X2  y  W1  W2  b")
    for x in data:
        x1, x2, y = x
        print(f"{x1}  {x2}  {y}  {w[0]}  {w[1]}  {bias}")
        w += np.array([x1, x2]) * y
        bias += y
    print(f"Trained Weights: w1={w[0]}, w2={w[1]}, bias={bias}")
    return w, bias

def test_hebbian(data, w, bias):
    print(f"X1  X2  W1  W2  b  Y")
    for x in data:
        x1, x2, y = x
        net = np.dot(w, np.array([x1, x2])) + bias
        r = 1 if net >= 0 else -1
        print(f"{x1}  {x2}  {w[0]}  {w[1]}  {bias}  {r}")

# Training Data (Inputs and Expected Outputs)
data = np.array([
    [-1, -1, -1],  # AND(-1, -1) -> -1
    [-1,  1, -1],  # AND(-1,  1) -> -1
    [ 1, -1, -1],  # AND( 1, -1) -> -1
    [ 1,  1,  1]   # AND( 1,  1) -> 1
])

# Train the model
weights, bias = train_hebbian(data)

# Test the model
test_hebbian(data, weights, bias)


X1  X2  y  W1  W2  b
-1  -1  -1  0.0  0.0  0
-1  1  -1  1.0  1.0  -1
1  -1  -1  2.0  0.0  -2
1  1  1  1.0  1.0  -3
Trained Weights: w1=2.0, w2=2.0, bias=-2
X1  X2  W1  W2  b  Y
-1  -1  2.0  2.0  -2  -1
-1  1  2.0  2.0  -2  -1
1  -1  2.0  2.0  -2  -1
1  1  2.0  2.0  -2  1


In [6]:
# Adaline Learning for AND Gate

# Training Data (Inputs and Expected Outputs)
data = [
    [-1, -1, -1],  # AND(-1, -1) -> -1
    [-1,  1, -1],  # AND(-1,  1) -> -1
    [ 1, -1, -1],  # AND( 1, -1) -> -1
    [ 1,  1,  1]   # AND( 1,  1) -> 1
]

# Initialize weights and bias
w = [0.0, 0.0]  # Weight vector for two inputs
bias = 0.0
learning_rate = 0.1

# Training Phase (Adaline)
print(f"X1  X2  y  W1  W2  b  Y")
for epoch in range(10):  # Run for 10 epochs
    for x1, x2, y in data:
        # Calculate net input (linear output before activation)
        net = w[0] * x1 + w[1] * x2 + bias

        # Calculate the predicted output
        predicted = net  # Since Adaline doesn't apply a step function

        # Calculate the error (difference between target and predicted)
        error = y - predicted

        # Update weights and bias using the Adaline learning rule
        w[0] += learning_rate * error * x1
        w[1] += learning_rate * error * x2
        bias += learning_rate * error

        # Print weights, bias, and error during training
        print(f"{x1}  {x2}  {y}  {w[0]}  {w[1]}  {bias}  {predicted}")

# Final trained weights and bias
print(f"Trained Weights: w1={w[0]}, w2={w[1]}, bias={bias}")

# Testing Phase (Adaline)
print(f"X1  X2  W1  W2  b  Y")
for x1, x2, y in data:
    net = w[0] * x1 + w[1] * x2 + bias
    predicted = net  # Adaline output
    print(f"{x1}  {x2}  {w[0]}  {w[1]}  {bias}  {predicted}")


X1  X2  y  W1  W2  b  Y
-1  -1  -1  0.1  0.1  -0.1  0.0
-1  1  -1  0.19  0.009999999999999995  -0.19  -0.1
1  -1  -1  0.091  0.109  -0.28900000000000003  -0.010000000000000009
1  1  1  0.1999  0.21789999999999998  -0.18010000000000004  -0.08900000000000002
-1  -1  -1  0.24011  0.25811  -0.22031000000000003  -0.5979
-1  1  -1  0.319879  0.178341  -0.30007900000000004  -0.20231000000000002
1  -1  -1  0.23573310000000003  0.26248689999999997  -0.38422490000000004  -0.15854100000000002
1  1  1  0.32433359000000006  0.35108739  -0.29562441  0.11399509999999996
-1  -1  -1  0.32722905100000005  0.353982851  -0.298519871  -0.97104539
-1  1  -1  0.40005244390000005  0.2811594581  -0.3713432639  -0.27176607100000005
1  -1  -1  0.32529747171000006  0.35591443029  -0.44609823609  -0.2524502780999999
1  1  1  0.40178610511900004  0.43240306369899995  -0.36960960268099996  0.23511366591000005
-1  -1  -1  0.38140622796910006  0.4120231865491  -0.3492297255311  -1.203798771499
-1  1  -1  0.44954495127